RustAudio/vst-rs

- examples/sine_synth/src/lib.rs
- src/api.rs
An implementation of the events iterator which does not need impl Trait. This allows users of the crate to access the events without resorting to either nightly or unsafe.
I think of this implementation as a temporary solution while we wait for impl Trait. When impl Trait lands on stable, we can go back to the previous, more elegant, solution. Users should not need to change their code at that point, as along as they are just iterating over whatever the events() method returns (which should be the common use case).
> Stable safe events

- .travis.yml
This change relies on a `TOKEN` already set on the webapp.  This should correctly trigger doc rebuilds when updates are pushed to master.  Should fix #7.
It's important to note that as of now, doc rebuilding will trigger whenever Travis succeeds, meaning that AppVeyor (and therefore Windows) may still fail.  This PR hasn't changed that (it was always that way), but it may be worth looking into for the future.
> Updated for docs to work

- examples/sine_synth.rs
Fix proposed in https://github.com/rust-dsp/rust-vst/issues/20
Also added a test for verifying that all valid midi notes don't crash.
Fixes https://github.com/rust-dsp/rust-vst/issues/20
> Fix sine synth underflow

- Cargo.toml
- examples/fwd_midi.rs
- src/buffer.rs
- src/interfaces.rs
- src/lib.rs
Now it's easier to use and will always send the correct number of events.
Before, it was possible to accidentally call `Host::process_events` before calling `SendEventBuffer::store` (or `store_midi`) which would cause the buffer contents to be sent from the last time that `store` or `store_midi` was called. 
And before, if `Host::process_events` would be called before any call to `store` or `store_midi`, it would have send a full buffer of zeroed out `SysExEvent`s (`num_events` would still have been `capacity` (i.e. 1024 in the default case) from `new()`). 
Now by making `SendEventBuffer::events()` private and only using it in `SendEventBuffer::send_events()` after having called `store_events` which calls `set_num_events` to set the correct number of events, it's now impossible to call …
> Improved midi sending: SendEventBuffer::send_events()

- src/plugin.rs
I'm using this successfully in my Reaper VST, e.g.:
```rust
#[derive(new)]
pub struct ReaperHost(HostCallback);
impl ReaperHost {
/// Get a pointer to the Reaper extension function by name (when running in Reaper)
#[allow(overflowing_literals)]
fn get_reaper_fn<F>(&self, func: &str) -> Option<F> {
let callback = self.0.raw_callback().unwrap_or_else(|| panic!("Host not yet initialized."));
use std::ffi::CString;
use std::mem::transmute_copy;
let f = callback(self.0.raw_effect(), 0xdeadbeef, 0xdeadf00d, 0, CString::new(func).unwrap().as_ptr() as _, 0.) as *const ();
if f.is_null() { None } else { Some(unsafe { transmute_copy(&f) }) }
}
pub fn get_api(&self) -> Option<ReaperApi> {
macro_rules! load {
(@ $f:tt) => { let $f: $f = self.get_reaper_fn(stringify!(f))?; };
($($fs:tt,)+) => { …
```
> Raw host callback access, for accessing host specific functionality, e.g. the Reaper Extension API

- src/buffer.rs
- src/host.rs
Creation of an AudioBuffer in a host is currently unsound, since the method to do so takes raw pointers and thus can't guarantee safety.
This PR is a suggestion for an API change making AudioBuffer creation in a host completely safe and sound.
The AudioBuffer needs two internal raw pointer arrays pointing to the actual input and output buffers. The lengths of these arrays correspond to the number of inputs and outputs, respectively. To keep the creation of the AudioBuffer allocation free, these buffers must be allocated up front. This is the job of the HostBuffer.
Whenever an AudioBuffer is needed, the HostBuffer is bound to the actual float arrays, and the AudioBuffer borrows the HostBuffer to ensure exclusive access to the HostBuffer arrays.
Example code is provided in the HostBuffer …
> Safe creation of AudioBuffer in the host

- src/interfaces.rs
- src/plugin.rs
`CanDo::from_str` was implemented in such a way that it was infallible, but the return type was still `Result<CanDo, String>`. Maybe the code was written like this to allow extending it to fail later? But if not, I thought it could be simplified and make the method more exactly express what it returns. This then also simplifies its usage.
> Make CanDo::from_str infallible

- examples/simple_host.rs
Allow the user to specify the path to a vst as first
parameter on the command line.
Example:
`simple_host ~/Library/Audio/Plug-Ins/foo.vst/Contents/MacOS/foo`
> Add command line option for simple_host

- src/api.rs
- src/host.rs
- src/interfaces.rs
- src/plugin.rs
This PR implements @Boscop's suggestions from #32 .
I would also propose to implement a time signature type like [time_calc's TimeSig](https://docs.rs/time_calc/0.13.0/time_calc/time_sig/struct.TimeSig.html)  to make `TimeInfo` a bit more high-level.
Closes #32.
> Follow up on PR #32 to implement GetTimeInfo and others

- src/plugin.rs
`is_effect_valid()` was turning `*mut AEffect` itself into an `i32` and comparing it with `VST_MAGIC`.
What needs to happen instead is you need to fetch `magic` out of the `AEffect` struct and compare *that* with `VST_MAGIC`.
I believe this is the more correct way of doing it over what #64 and #47 have.
Also, comments in Telegram suggest we might just be able to remove the function entirely, which I can do if that's the desired change.
I tested this as part of my X11 GUI development - before this change, parameters were not updating in the DAW when you changed them via the GUI; after this change, they updated successfully.
> Fix HostCallback::is_effect_valid()

- .appveyor.yml
- .travis.yml
Looks like the toolchain specification syntax we were using previously no longer works
> Update CI builds to use stable only

- README.md
- src/editor.rs
- src/interfaces.rs
`dispatch()` should return 1 if the editor was opened successfully. Some DAWs ignore this return value, but others don't.
One example of a DAW that doesn't is Carla ([see this chunk of code](https://github.com/falkTX/Carla/blob/51f20736b4e0b5d6416f2b7d4051f155f5858fbf/source/backend/plugin/CarlaPluginVST2.cpp#L513)).
Since we return 0 here by default, Carla assumes that the editor failed to open.
I think the more correct way to do this would be to actually check that `editor.open()` was successful in some way, but that would require an API change.
> OpCode::EditorOpen: return 1 if editor opened successfully

- Cargo.toml
- src/lib.rs
- src/util/atomic_float.rs
- src/util/mod.rs
- src/util/parameter_transfer.rs
This is a couple of structs to make it easier to handle the communication between the UI and processing threads. In particular, they will help when porting VST plugins from the old to the new API after https://github.com/rust-dsp/rust-vst/pull/65 lands. The plan is to add an example (based on [transfer_and_smooth](https://github.com/askeksa/transfer_and_smooth)) containing a detailed guide on how to port an existing plugin using [`ParameterTransfer`](https://github.com/askeksa/rust-vst/blob/utility_module/src/util/parameter_transfer.rs).
Before merging this, I would like some feedback on these issues:
1. General proofreading of the documentation. Is it adequate?
2. The [`AtomicFloat`](https://github.com/askeksa/rust-vst/blob/utility_module/src/util/atomic_float.rs) struct is specialized …
> Utility structs to make it easier to make plugins thread safe.

- examples/dimension_expander.rs
- examples/gain_effect.rs
- examples/transfer_and_smooth.rs
- src/api.rs
- src/buffer.rs
- src/cache.rs
- src/host.rs
- src/interfaces.rs
- src/lib.rs
- src/plugin.rs
For improved clarity in the code and examples, use the new `dyn` syntax for all trait objects.
This ups the minimum required Rust version for the crate to 1.27, which is 10 months old.
> Use dyn syntax for trait objects.

- src/plugin.rs
Fixes the issue with parameters not showing up in Bitwig.
In my opinion, there's no reason to have non-automatable parameters exposed to the host. If a plugin needs hidden state, manage it internally.
> Parameters should be automatable by default

- src/interfaces.rs
Bitwig wasn't getting the VST's name anymore:
I assume this is because Bitwig *used to* issue a `GetProductName` opcode to get this, but now it's issuing the `GetEffectName` opcode instead.
I simply copy-pasted what we had for `GetProductName` and made it the `GetEffectName` handler too:
I know that Carla/JUCE [uses this same opcode to fill in the plugin name](https://github.com/falkTX/Carla/blob/0038f94bf28b4a09ad4df9121e1fab19c02eadfb/source/modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp#L600) (they call their equivalent opcode `plugInOpcodeGetPlugInName` [here](https://github.com/falkTX/Carla/blob/0038f94bf28b4a09ad4df9121e1fab19c02eadfb/source/modules/juce_audio_processors/format_types/juce_VSTInterface.h#L126)).
I couldn't find out what `GetProductName` is …
> Handle Opcode::GetEffectName

- src/api.rs
Fixes [this test case](https://gist.github.com/zopu/61919c5eb6354ff0faf7df2959ab351b). 
I added `#[allow(dead_code)]` since it appears that several people are using the `events_raw` method in their own code rather than the iterator.
> Fix for a use-after-move bug when calling Events::events  more than once

- src/api.rs
Adds some tests written while debugging the issue fixed in PR #93
> Adds some tests for api::Event code

- src/util/atomic_float.rs
- src/util/parameter_transfer.rs
Original code used `AtomicUsize` (wasting space in 64-bit builds) only because `AtomicU32` wasn't stable at the time. It is now (as of Rust 1.34).
> Use AtomicU32 for atomic float values

- src/buffer.rs
- src/host.rs
This fixes a clippy lint for `std::mem::uninitialized` which has been deprecated.
> replaced mem::uninitialized with mem::MaybeUninit and added an #[allow] for clippy 

- src/api.rs
As discussed on discord, this removes the `EventIterator` struct and replaces it using the `impl Trait` return syntax.
> removed EventIterator and replaced with impl Trait syntax

- README.md
- src/lib.rs
A bit more information up front in the documentation about how to connect the `Plugin` and `PluginParameters` implementations, plus a prominent note in the readme about porting old plugin code.
> More documentation about thread-safe API update

- .travis.yml
- src/interfaces.rs
- src/lib.rs
Plugin should return `1` if it has editor on `EditorGetRect` opcode, otherwise provided dimensions won't be applied by host.
> Fix `EditorGetRect` opcode

- examples/simple_host.rs
- src/host.rs
- src/interfaces.rs
- src/lib.rs
- src/plugin.rs
Reopens #125
I'm not currently using vst-rs anymore, so I won't be able to properly test this. I'll gladly accept fixes and suggestions before merging.
cc @askeksa
> Document and add `update_display` to Host

- src/api.rs
- src/plugin.rs
Background: [Cockos Extensions to VST SDK](http://reaper.fm/sdk/vst/vst_ext.php) defines some non-standard behavior controlled via custom `can_do()` return values (other than 1, 0 or -1). I'm currently using this in [ReaLearn](https://github.com/helgoboss/realearn/blob/a7ccda9f5bd27738b40e15f084dfaacc671b299f/src/infrastructure/plugin/realearn_plugin.rs#L119).
> Allow plug-in to return a custom value in can_do()

- src/host.rs
- src/plugin.rs
This pull request implements a few editor related functions for `PluginInstance`:
- `get_editor_rect()`
- `open_editor()`
- `close_editor()`
I'm writing a VST plugin host GUI application using `vst-rs` and find these functions useful.
> Implement a few editor related functions for PluginInstance

- src/api.rs
Introduce zero-valued EventType to enable zero-initialization of Event.
Fixes https://github.com/RustAudio/vst-rs/issues/131
> Introduce zero-valued EventType to enable zero-initialization of Event

- src/util/atomic_float.rs
Default value for AtomicFloat.
Fixes https://github.com/RustAudio/vst-rs/issues/137
> Default value for AtomicFloat

- src/host.rs
- src/interfaces.rs
- src/plugin.rs
@wrl told me, that plugin Hosts are expecting BeginEdit and EndEdit if a user touches a parameter knob.
Here is a patch to add and document convenience functions for this.
> Host begin end edit

- src/editor.rs
- src/host.rs
- src/interfaces.rs
- src/plugin.rs
The plugin seems to crash if I type a non special key like 'a' in a host like Ardour.
The problem is, that the key "0" is not mapped to any Key enum.
The correct fix would be to support `keyboard_types` crate (like baseview), but that's maybe for later.
> Key character fix

- src/api.rs
- src/host.rs
- src/interfaces.rs
- src/plugin.rs
**Breaking change**: Require `Plugin` to be `Send`, since its methods can be called from different threads at different times.
Restructure dispatch code to avoid obtaining concurrent `&mut` references to the `Plugin` or `Editor`.
Fixes https://github.com/RustAudio/vst-rs/issues/132
> Require Plugin to be Send, avoid concurrent &mut

- src/api.rs
- src/host.rs
- src/interfaces.rs
- src/lib.rs
- src/plugin.rs
Mark function pointers in AEffect as extern, since these are called directly from C code.
Fixes warning about `HostCallbackProc` being passed as parameter to an `extern` function.
> Mark function pointers in AEffect as extern, since these are called directly from C code.

- README.md
- examples/dimension_expander.rs
- examples/fwd_midi.rs
- examples/gain_effect.rs
- examples/ladder_filter.rs
- examples/sine_synth.rs
- examples/transfer_and_smooth.rs
- src/api.rs
- src/buffer.rs
- src/host.rs
- src/lib.rs
- src/plugin.rs
fixes https://github.com/RustAudio/vst-rs/issues/153 by implementing `Plugin::new` for `PluginInstance` by using `unreachable!()`.
It's safe because it's never called anyway. 
(`Plugin::new` is only called on the client side and `PluginInstance` is only used on the host side):
https://github.com/Boscop/rust-vst/blob/0da6e719a26ba67d8302caf26eda1539ee221e81/src/host.rs#L570
> Don't require Plugin to impl Default

- examples/fwd_midi.rs
- src/buffer.rs
This PR makes `SendEventBuffer::store_events` and `SendEventBuffer::events` public, so that `SendEventBuffer` can be used to feed midi input events from `Plugin::process_events` to `Plugin::process` without allocating memory each frame. 
(See the adjusted `fwd_midi` example, which now doesn't allocate memory each frame for the midi events, but uses `SendEventBuffer` for midi input events.)
I also removed the (now unused) `send_events_to_plugin` method (which was used a while ago when `SendEventBuffer` was a member in `PluginCache` to feed midi events to `Plugin::process_events`).
> Rework `SendEventBuffer` to make it useable in `Plugin::process_events`

- examples/dimension_expander.rs
- examples/fwd_midi.rs
- examples/gain_effect.rs
- examples/ladder_filter.rs
- examples/sine_synth.rs
- examples/transfer_and_smooth.rs
- src/lib.rs
- src/plugin.rs
- src/prelude.rs
This PR adds a `prelude.rs` with some commonly used types and traits as a sort of demo of @Boscop's [suggestion](https://github.com/RustAudio/vst-rs/issues/156). I've had a look around this crate and tried writing a couple of VST plugins before looking at this. The selection of items was based on that and the provided examples. That being said, it might be a bit excessive to include certain things, e.g. `Event`.
> Add prelude for commonly used items

- CHANGELOG.md
- Cargo.toml
- README.md
Add a deprecation notice to the README (as discussed in #193), bump the crate version so the notice can be published to crates.io, and update the changelog accordingly.
> Add deprecation notice to README and bump version to 0.4.0

- Cargo.toml
- src/plugin.rs
So you can't miss it. The `disable_deprecation_warning` feature can be used to disable the warning if the user has a really good reason to still use the `vst` crate, but it's intentionally undocumented.
This would be part of the 0.4.0 update (I saw nothing had actually been tagged yet).
> Add the deprecated attribute to the Plugin trait
